### PR TITLE
Update sshkit

### PR DESCRIPTION
**Pull request by berkos**
Versions of SSHKit < 1.11 are not compatible with Ruby 2.4+

### CODE REVIEW

**Comment by timstott** [comment]
@berkos is this really you? How can we be sure now!

> GPG key ID: 318C69E18A7076F0
> The key that signed this is expired.

**Comment by berkos** [comment]
@timstott  You are so right! ❤️

**Comment by berkos** [comment]
Fixes https://github.com/FundingCircle/sshkit-backends-netssh_global/issues/3

**Comment by dideler** [comment]
Don't forget to ship! :ship:

**Pull request merged**
